---
k8s-monitoring:
  cluster:
    name: "raspberry"

  global:
    kubernetesAPIService: "localhost:7445"

  destinations:
    - name: victoriaMetrics
      type: otlp
      protocol: http
      url: http://vmsingle-victoria-metrics-k8s-stack:8428/opentelemetry/v1/metrics
      logs:
        enabled: false
      traces:
        enabled: false
      metrics:
        enabled: true
    - name: victoriaLogs
      type: otlp
      protocol: http
      url: http://victoria-logs-victoria-logs-single-server:9428/insert/opentelemetry/v1/logs
      logs:
        enabled: true
      traces:
        enabled: false
      metrics:
        enabled: false

  clusterMetrics:
    enabled: true

  clusterEvents:
    enabled: true

  podLogsViaKubernetesApi:
    enabled: true

  annotationAutodiscovery:
    enabled: true

  alloy-metrics:
    enabled: true

  alloy-singleton:
    enabled: true

  alloy-logs:
    enabled: true

  alloy-operator:
    deploy: true

    waitForAlloyRemoval:
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          memory: 128Mi
