---
apiVersion: v2
name: kube-prometheus-stack
description: A Helm chart for Kubernetes
type: application
version: 79.5.0
dependencies:
  - name: kube-prometheus-stack
    version: 79.5.0
    repository: "https://prometheus-community.github.io/helm-charts"
